"""Paso 1: escribir header + enum + dataclass"""
import pathlib
p = pathlib.Path("services/pdf_remision_service.py")
p.write_text(
'"""Servicio de PDFs de remision: reimpresion dinamica con seleccion de modo de valores."""\n'
'from __future__ import annotations\n'
'\n'
'import asyncio\n'
'import logging\n'
'import re\n'
'import tempfile\n'
'from dataclasses import dataclass\n'
'from datetime import datetime\n'
'from enum import Enum\n'
'from pathlib import Path\n'
'from typing import Any, Dict, List, Optional, Tuple\n'
'\n'
'logger = logging.getLogger(__name__)\n'
'_RE_NUMERO = re.compile(r"[A-Za-z]*[_\\-\\s]?(\\d+)\\b", re.IGNORECASE)\n'
'_PREFIJO = "REM_"\n'
'\n'
'\n'
'class ModoImpresion(str, Enum):\n'
'    MONEDA_LOCAL = "moneda_local"\n'
'    DOLARES = "dolares"\n'
'    AMBAS = "ambas"\n'
'    SIN_VALORES = "sin_valores"\n'
'\n'
'\n'
'MAPA_MODOS_IMPRESION: Dict[str, ModoImpresion] = {\n'
'    "1": ModoImpresion.MONEDA_LOCAL, "local": ModoImpresion.MONEDA_LOCAL, "cop": ModoImpresion.MONEDA_LOCAL,\n'
'    "2": ModoImpresion.DOLARES, "usd": ModoImpresion.DOLARES, "dolares": ModoImpresion.DOLARES,\n'
'    "3": ModoImpresion.AMBAS, "ambas": ModoImpresion.AMBAS, "todo": ModoImpresion.AMBAS,\n'
'    "4": ModoImpresion.SIN_VALORES, "sin_valores": ModoImpresion.SIN_VALORES,\n'
'    "limpio": ModoImpresion.SIN_VALORES, "ninguno": ModoImpresion.SIN_VALORES,\n'
'}\n'
'\n'
'@dataclass(frozen=True)\n'
'class RemisionPdf:\n'
'    numero_remision: str\n'
'    pdf_url: str\n'
'    cliente: str\n'
'    fecha_creacion: Optional[str] = None\n'
'\n'
'    @property\n'
'    def filename(self) -> str:\n'
'        return f"{self.numero_remision}.pdf"\n'
'\n'
'    @property\n'
'    def caption(self) -> str:\n'
'        c = (self.cliente or "").strip() or "Sin cliente"\n'
'        return f"Remision {self.numero_remision} - {c}"\n'
'\n'
'\n'
'class PdfRemisionError(Exception): pass\n'
'class PdfRemisionNoEncontrada(PdfRemisionError): pass\n'
'class PdfDescargaError(PdfRemisionError): pass\n',
encoding="utf-8")
print("g1 OK:", p.stat().st_size, "bytes")
